name: Release Jira Version
description: Releases a Jira Version
branding:
  icon: arrow-up
  color: green
inputs:
  project:
    required: true
    description: Jira Project Key (e.g. FW)
  version:
    required: true
    description: Jira Version Name (e.g. PROD-80)
  user:
    required: true
    description: Jira username
  password:
    required: true
    description: Jira user password
  url:
    required: true
    description: Jira base url
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        python "${{ github.action_path }}/../../jira.py" \
          --base-url="${{ inputs.url }}" \
          --username="${{ inputs.user }}" \
          --password="${{ inputs.password }}" \
          release-version \
          --project="${{ inputs.project }}" \
          --version="${{ inputs.version }}"
