# Version: 2024-06-13
# This is an organization workflow, it should not be edited!
# The original source is in the baltech-ag/ci-scripts repository in the templates folder
# https://baltech-wiki.atlassian.net/wiki/spaces/THIR/pages/257785857/GitHub#GitHub-Workflows-f%C3%BCr-Releasemanagement-einrichten
name: Release Actions
on:
  push:
  pull_request:
    branches:
      - 'master'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9][0-9][0-9][0-9]-[0-9]+.[0-9]+'
    types:
      - 'closed'
  create:
jobs:
  release-actions:
    uses: baltech-ag/ci-scripts/.github/workflows/release-actions.yml@master
    secrets: inherit
  deploy-build:
    needs: [release-actions]
    if: github.event_name == 'push'
    uses: ./.github/workflows/repo-release-actions-deploy.yml
    with:
      release-stage: ${{ needs.release-actions.outputs.release-stage }}
      deploy-mode: ${{ needs.release-actions.outputs.deploy-mode }}
      project-name: ${{ needs.release-actions.outputs.project-name }}
      sub-project-id: ${{ needs.release-actions.outputs.sub-project-id }}
      version: ${{ needs.release-actions.outputs.version }}
      version-file: ${{ needs.release-actions.outputs.version-file }}
    secrets: inherit
