# This workflow is called from the workflow org-release-actions.yml, do not change its filename
# https://baltech-wiki.atlassian.net/wiki/spaces/THIR/pages/257785857/GitHub#GitHub-Workflows-f%C3%BCr-Releasemanagement-einrichten
name: Release Actions - Deploy build
on:
  workflow_call:
    inputs:
      release-stage: # one of branch-created|pr-merged|tag-pushed
        type: string
        required: true
      deploy-mode: # one of development|release
        type: string
        required: true
      project-name:
        type: string
        required: true
      sub-project-id:
        type: string
        required: false
      version:
        type: string
        required: true
      version-file:
        type: string
        required: true
jobs:
  create-build:
    name: Create build
    runs-on: ...
    steps:
      ...
  deploy-build:
    name: Deploy build
    needs: [create-build]
    runs-on: ...
    steps:
      ...
