name: "Jira Comment"
description: "Adds a Comment to an Jira Issue"
branding:
  icon: message-square
  color: blue
inputs:
  comment_file:
    required: true
    description: "Path to a json file with the comments (dict with issue as key and comment as value)"
  user:
    required: true
    description: "Jira username"
  password:
    required: true
    description: "Jira user password"
  url:
    required: true
    description: "Jira base url"
runs:
  using: composite
  steps:
    - shell: bash
      run: python "${{ github.action_path }}/../../jira_comment.py"
      env:
        JIRA_COMMENT_FILE: "${{ inputs.comment_file }}"
        JIRA_URL: "${{ inputs.url }}"
        JIRA_USER: "${{ inputs.user }}"
        JIRA_PASSWORD: "${{ inputs.password }}"
