name: Jira Version Exists
description: Checks if a Jira Version exists
branding:
  icon: check-square
  color: blue
inputs:
  project:
    required: true
    description: Jira Project Key (e.g. FW)
  version:
    required: true
    description: Jira Version Name (e.g. PROD-80)
  user:
    required: true
    description: Jira username
  password:
    required: true
    description: Jira user password
  url:
    required: true
    description: Jira base url
outputs:
  exists:
    description: 1 if the Issue exists else 0
    value: ${{ steps.check.outputs.exists }}
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        version=`python "${{ github.action_path }}/../../jira.py" \
          --base-url="${{ inputs.url }}" \
          --username="${{ inputs.user }}" \
          --password="${{ inputs.password }}" \
          get-version \
          --project="${{ inputs.project }}" \
          --version="${{ inputs.version }}"`
        
        if [[ $version ]]; then
          echo "exists=1" >> $GITHUB_OUTPUT
        else
          echo "exists=0" >> $GITHUB_OUTPUT
        fi
