on:
  workflow_call:
jobs:
  jira-integration-push:
    name: Comment pushed commit messages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout ci-scripts repository
        uses: actions/checkout@v3
        with:
          repository: baltech-ag/ci-scripts
          path: ci-scripts
      - name: Jira integration
        run: python ci-scripts/jira_integration_push.py
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          CI_SERVER_URL: ${{ github.repositoryUrl }}
          CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
          CI_COMMIT_SHA: ${{ github.event.after }}
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
          CI_PROJECT_NAMESPACE: ${{ github.repository_owner }}
          CI_PROJECT_DIR: ${{ github.workspace }}
      - name: Cleanup
        if: always()
        run: rm -rf ci-scripts
