on:
  workflow_call:
    inputs:
      sha_before:
        required: true
        type: string
      sha_after:
        required: true
        type: string
      ref_name:
        required: true
        type: string
      project_dir:
        required: true
        type: string
      project_name:
        required: true
        type: string
      project_namespace:
        required: true
        type: string
      server_url:
        required: true
        type: string
jobs:
  jira-integration:
    name: Validate commit messages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout ci-scripts repository
        uses: actions/checkout@v3
        with:
          repository: baltech-ag/ci-scripts
          path: ci-scripts
      - name: Jira integration
        run: python ci-scripts/ci-scripts/jira_integration.py
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          CI_SERVER_URL: ${{ input.server_url }}
          CI_COMMIT_BEFORE_SHA: ${{ input.sha_before }}
          CI_COMMIT_SHA: ${{ input.sha_after }}
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          CI_PROJECT_NAME: ${{ project_name }}
          CI_PROJECT_NAMESPACE: ${{ project_namespace }}
          CI_PROJECT_DIR: ${{ input.workspace }}
      - name: Cleanup
        if: always()
        run: rm -rf ci-scripts
