name: Release Actions - Create PR
on:
  workflow_call:
    inputs:
      ci-scripts-ref:
        type: string
        required: false
        default: master
jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(fromJson('["release-major", "release-minor", "release-patch"]'), github.head_ref) && !startsWith(github.event.head_commit.message, '[release]') }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BALTECH_BOT_ID }}
          private-key: ${{ secrets.BALTECH_BOT_KEY }}
      - name: Configure git
        run: |
          git config --global url.https://${{ steps.generate-token.outputs.token }}@github.com/.insteadOf https://github.com/
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout ci-scripts repository
        uses: actions/checkout@v4
        with:
          repository: baltech-ag/ci-scripts
          ref: ${{ inputs.ci-scripts-ref }}
          path: ci-scripts
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Restore tox environment from cache
        id: tox-cache
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('poetry.lock') }}
      - name: Update version
        run: python ci-scripts/release_actions.py prepare-next-version
        env:
          CI_PROJECT_NAME: ${{ github.event.repository.name }}
          CI_BRANCH_NAME: ${{ github.ref_name }}
      - name: Get version
        id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Create PR for release branch
        run: |
          gh pr create --base master --head ${{ github.ref }} --title "[release] ${{ github.event.repository.name }} ${{ steps.get-version.outputs.version }}" --body "" --assignee "${{ github.actor }}"
          gh pr merge ${{ github.ref_name }} --rebase --auto
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Cleanup
        if: always()
        run: rm -rf ci-scripts
