name: Release Actions - Deploy build to OneDrive
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
      artifact-file-name:
        type: string
        required: true
      projects-folder:
        type: string
        required: true
      project-name:
        type: string
        required: true
      file-extension:
        type: string
        required: true
jobs:
  deploy-onedrive:
    name: Deploy build to OneDrive
    runs-on: [self-hosted, windows, onedrive]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Read project version
        id: version
        run: ("version=" + (Get-Content VERSION).replace(".", "_")) | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Deploy
        shell: cmd
        run: |
          setlocal EnableDelayedExpansion
          set "SOURCE=${{ steps.download-artifact.outputs.download-path }}\${{ inputs.artifact-file-name }}"
          echo Source file: !SOURCE!
          set "DEST=%OneDriveCommercial%\F&E\Projekte\${{ inputs.projects-folder }}\${{ inputs.project-name }}\bin\${{ inputs.project-name }}_${{ steps.version.outputs.version }}${{ inputs.file-extension }}"
          echo Destination file: !DEST!
          copy "!SOURCE!" "!DEST!"
